# Let's Practice Numpy in Python

In [1]:
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
import numpy as np
a=np.array([[1,2,3], [4,5,6]])
a


array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
import numpy as np
a=np.array([[1,2,3], [4,5,6]])
type(a)


numpy.ndarray

In [10]:
import numpy as np
a=np.array([[1,2,3], [4,5,6],[7,8,9]])
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
len(a)

3

In [12]:
a[0]

array([1, 2, 3])

In [13]:
a[2]

array([7, 8, 9])

In [15]:
a[:0]

array([], shape=(0, 3), dtype=int32)

In [16]:
a[0:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
b=np.zeros(3)
b

array([0., 0., 0.])

In [19]:
c=np.ones(5)
c

array([1., 1., 1., 1., 1.])

In [20]:
d=np.empty(5)
d

array([1., 1., 1., 1., 1.])

In [24]:
e=np.empty(0)
e

array([], dtype=float64)

In [25]:
#array with specific range
d=np.arange(10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
f=np.arange(2,15)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
#linear spaced array
h=np.linspace(5,50, num=10)
h

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [35]:
#specific data type in array
g=np.ones(5, dtype=np.int32)
g

array([1, 1, 1, 1, 1])

In [32]:
#specific data type in array
g=np.ones(3, dtype=np.float64)
g

array([1., 1., 1.])

In [41]:
k=np.ones((3,2))
k


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [42]:
k=np.zeros((3,3))
k


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## - 3D array

In [52]:
z=np.arange(24).reshape(2,3,4)
z

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [2]:
import numpy as np
c= np.arange(32).reshape(2,4,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [5]:
import numpy as np
food=np.array(['pakora', 'samosa', 'chatni'])
food

array(['pakora', 'samosa', 'chatni'], dtype='<U6')

In [7]:
type(food)

numpy.ndarray

In [8]:
len(food)

3

In [9]:
food[1]

'samosa'

In [17]:
np.empty([4,4])

array([[4.67296746e-307, 1.69121096e-306, 8.01095173e-307,
        7.56603203e-307],
       [1.42413555e-306, 1.78019082e-306, 1.37959740e-306,
        6.23057349e-307],
       [1.42419530e-306, 2.22522597e-306, 1.33512173e-306,
        1.22387126e-307],
       [6.23036978e-307, 9.45697982e-308, 8.90074530e-308,
        1.42410974e-306]])

In [18]:
h=np.linspace(5,100, num=10)
h

array([  5.        ,  15.55555556,  26.11111111,  36.66666667,
        47.22222222,  57.77777778,  68.33333333,  78.88888889,
        89.44444444, 100.        ])

## Array functions 

In [3]:
import numpy as np
b=np.array([4,5.6,5,7.2])
b

array([4. , 5.6, 5. , 7.2])

In [4]:
type(b)

numpy.ndarray

In [5]:
b.sort()

In [6]:
b

array([4. , 5. , 5.6, 7.2])

In [7]:
a=np.array([[1,2,3], [4,5,6]])
a


array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
c=np.array([[2,4,7], [4,5,6]])
c


array([[2, 4, 7],
       [4, 5, 6]])

In [14]:
np.concatenate((a,c), axis=1)

array([[1, 2, 3, 2, 4, 7],
       [4, 5, 6, 4, 5, 6]])

In [15]:
c.size

6

In [16]:
c.ndim

2

In [17]:
c.shape

(2, 3)

In [21]:
d=c[np.newaxis,:]
d

array([[[2, 4, 7],
        [4, 5, 6]]])

In [22]:
d=c[:,np.newaxis]
d

array([[[2, 4, 7]],

       [[4, 5, 6]]])

In [23]:
d.sum()

28

In [24]:
d.mean()

4.666666666666667

In [25]:
d

array([[[2, 4, 7]],

       [[4, 5, 6]]])

In [26]:
d=c[:,np.newaxis]
d

array([[[2, 4, 7]],

       [[4, 5, 6]]])

In [27]:
p=np.array([1,2,4,6])
p

array([1, 2, 4, 6])

In [30]:
z=p[:,np.newaxis]
z

array([[1],
       [2],
       [4],
       [6]])

In [32]:
z.mean()

3.25

In [33]:
z.sum()

13